default:
  tags: [ 'bi-lab' ]

stages:
  - build
  - test
  - report
  - build-docker-images
  - deploy

cache:
  key: one-key-to-rule-them-all
  paths:
    - ./.m2/repository

# ------------------------------------------------------------------------------
# Stage "test"

test:
  image: clojure:openjdk-14-tools-deps-alpine
  before_script:
    - wget $DOWNLOAD_DEV_LOCAL && mkdir -p local_jars/dev-local && mv dev-local.jar local_jars/dev-local
  script:
    - clojure -Sdeps '{:mvn/local-repo "./.m2/repository"}' -A:test
  artifacts:
    paths:
      - target/coverage/lcov.info
    expire_in: 1 hour

test-cljs:
  image: clojure:openjdk-14-tools-deps-alpine
  before_script:
    - apk add yarn
    - yarn install
  script:
    - yarn shadow-cljs compile test

lint:
  image: clojure:openjdk-14-tools-deps-alpine
  before_script:
    - wget $DOWNLOAD_DEV_LOCAL && mkdir -p local_jars/dev-local && mv dev-local.jar local_jars/dev-local
  script:
    - clojure -Sdeps '{:mvn/local-repo "./.m2/repository"}' -A:clj-kondo --lint src
  allow_failure: true
  when: always

css-lint:
  image: node:14.8-alpine
  before_script:
    - yarn install --dev
  script:
    - yarn stylelint "resources/public/css/*.scss"
  allow_failure: true
  when: always

up-to-date?:
  image: clojure:openjdk-14-tools-deps-alpine
  before_script:
    - apk add git
    - wget $DOWNLOAD_DEV_LOCAL && mkdir -p local_jars/dev-local && mv dev-local.jar local_jars/dev-local
  script:
    - clojure -Sdeps '{:mvn/local-repo "./.m2/repository"}' -A:outdated
  allow_failure: true
  when: always


# ------------------------------------------------------------------------------
# Stage "report"

coverage-report:
  image: python:3-alpine
  stage: report
  script:
    - wget -O - https://s3.disqtec.com/schnaq-ci/lcov_cobertura.py | python3 - target/coverage/lcov.info --output target/coverage/coverage.xml
  artifacts:
    reports:
      cobertura: target/coverage/coverage.xml


# ------------------------------------------------------------------------------
# Stage "build-docker-images"

build-frontend-image:
  image: docker
  services:
    - docker:stable-dind
  stage: build-docker-images
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - >
      docker build -f Dockerfile.frontend
      --build-arg REST_API_URL=https://api.schnaq.com
      --build-arg BUILD_HASH=$CI_COMMIT_SHORT_SHA
      --build-arg KEYCLOAK_REALM=$KEYCLOAK_REALM
      --build-arg KEYCLOAK_CLIENT=$KEYCLOAK_CLIENT
      -t $CI_REGISTRY_IMAGE/frontend .
    - docker push $CI_REGISTRY_IMAGE/frontend
  only:
    - deploy

build-backend-image:
  image: docker
  services:
    - docker:stable-dind
  stage: build-docker-images
  before_script:
    - wget $DOWNLOAD_DEV_LOCAL && mkdir -p local_jars/dev-local && mv dev-local.jar local_jars/dev-local
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - >
      docker build -f Dockerfile.backend
      --build-arg BUILD_HASH=$CI_COMMIT_SHORT_SHA
      -t $CI_REGISTRY_IMAGE/backend .
    - docker push $CI_REGISTRY_IMAGE/backend
  only:
    - deploy

build-frontend-staging-image:
  image: docker
  services:
    - docker:stable-dind
  stage: build-docker-images
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - >
      docker build -f Dockerfile.frontend
      --build-arg REST_API_URL=https://api.staging.schnaq.com
      --build-arg BUILD_HASH=$CI_COMMIT_SHORT_SHA
      --build-arg KEYCLOAK_REALM=$KEYCLOAK_REALM_STAGING
      --build-arg KEYCLOAK_CLIENT=$KEYCLOAK_CLIENT_STAGING
      -t $CI_REGISTRY_IMAGE/frontend:staging .
    - docker push $CI_REGISTRY_IMAGE/frontend:staging
  only:
    - develop

build-backend-staging-image:
  image: docker
  services:
    - docker:stable-dind
  stage: build-docker-images
  before_script:
    - wget $DOWNLOAD_DEV_LOCAL && mkdir -p local_jars/dev-local && mv dev-local.jar local_jars/dev-local
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - >
      docker build -f Dockerfile.backend
      --build-arg BUILD_HASH=$CI_COMMIT_SHORT_SHA
      -t $CI_REGISTRY_IMAGE/backend:staging .
    - docker push $CI_REGISTRY_IMAGE/backend:staging
  only:
    - develop

deploy-staging:
  stage: deploy
  variables:
    DEPLOYMENT: staging
  trigger: dialogo/deployments/schnaq
  only:
    - develop

deploy-production:
  stage: deploy
  variables:
    DEPLOYMENT: production
  trigger: dialogo/deployments/schnaq
  only:
    - deploy