# Fallback: Use this tag when the cs servers are down.
#default:
#  tags: [ 'bi-lab' ]

stages:
  - build
  - test
  - report
  - build-docker-images
  - deploy

cache:
  key: one-key-to-rule-them-all
  paths:
    - ./.m2/repository
    - ./resources/public/node_modules

variables:
  BACKEND_IMAGE: $CI_REGISTRY_IMAGE/backend
  FRONTEND_IMAGE: $CI_REGISTRY_IMAGE/frontend
  BACKEND_IMAGE_TAGGED: $CI_REGISTRY_IMAGE/backend:$CI_PIPELINE_IID
  FRONTEND_IMAGE_TAGGED: $CI_REGISTRY_IMAGE/frontend:$CI_PIPELINE_IID

.with-datomic-pro:
  before_script:
    - mkdir -p ~/.m2
    - cp settings.xml ~/.m2/settings.xml

# ------------------------------------------------------------------------------
# Stage "test"

test:
  extends: .with-datomic-pro
  image: clojure:openjdk-17-tools-deps-slim-bullseye
  script:
    - clojure -Sdeps '{:mvn/local-repo "./.m2/repository"}' -A:test
  artifacts:
    paths:
      - target/coverage/lcov.info
    expire_in: 1 hour

test-cljs:
  extends: .with-datomic-pro
  image: ghcr.io/schnaq/clojure-yarn-chrome
  before_script:
    - yarn install
  script:
    - clj -Sdeps '{:mvn/local-repo "./.m2/repository"}' -M:test-cljs
    - yarn karma start --single-run

lint:
  extends: .with-datomic-pro
  image: clojure:openjdk-17-tools-deps-slim-bullseye
  script:
    - clojure -Sdeps '{:mvn/local-repo "./.m2/repository"}' -A:clj-kondo --lint src
  allow_failure: true
  when: always

css-compile-and-lint:
  image: ghcr.io/schnaq/clojure-yarn-chrome
  before_script:
    - yarn install --dev
    - yarn global add sass
  script:
    - yarn stylelint "resources/public/css/*.scss" --config-basedir "resources/public/node_modules/"
    - sass ./resources/public/css/main.scss ./resources/public/css/main.min.css --no-source-map --style compressed
  when: always

up-to-date?:
  extends: .with-datomic-pro
  image: clojure:openjdk-17-tools-deps-slim-bullseye
  script:
    - clojure -Sdeps '{:mvn/local-repo "./.m2/repository"}' -A:outdated
  allow_failure: true
  when: always

# ------------------------------------------------------------------------------
# Stage "report"

coverage-report:
  image: python:3-alpine
  stage: report
  script:
    - wget -O - https://s3.schnaq.com/schnaq-ci/lcov_cobertura.py | python3 - target/coverage/lcov.info --output target/coverage/coverage.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: target/coverage/coverage.xml

# ------------------------------------------------------------------------------
# Stage "build-docker-images"

build-frontend-image:
  extends: .with-datomic-pro
  image: docker
  tags:
    - ht
  services:
    - docker:dind
  stage: build-docker-images
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - >
      docker build -f Dockerfile.frontend --pull
      --build-arg REST_API_URL=https://api.schnaq.com
      --build-arg BUILD_HASH=$CI_COMMIT_SHORT_SHA
      --build-arg KEYCLOAK_REALM=$KEYCLOAK_REALM
      --build-arg KEYCLOAK_CLIENT=$KEYCLOAK_CLIENT
      --build-arg DATOMIC_REPO_USERNAME
      --build-arg DATOMIC_REPO_PASSWORD
      -t $FRONTEND_IMAGE_TAGGED .
    - docker tag $FRONTEND_IMAGE_TAGGED $FRONTEND_IMAGE:latest
    - docker push $FRONTEND_IMAGE_TAGGED
    - docker push $FRONTEND_IMAGE:latest
  only:
    - deploy

build-backend-image:
  extends: .with-datomic-pro
  image: docker
  tags:
    - ht
  services:
    - docker:dind
  stage: build-docker-images
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - >
      docker build -f Dockerfile.backend --pull
      --build-arg BUILD_HASH=$CI_COMMIT_SHORT_SHA
      --build-arg DATOMIC_REPO_USERNAME
      --build-arg DATOMIC_REPO_PASSWORD
      -t $BACKEND_IMAGE_TAGGED .
    - docker tag $BACKEND_IMAGE_TAGGED $BACKEND_IMAGE:latest
    - docker push $BACKEND_IMAGE_TAGGED
    - docker push $BACKEND_IMAGE:latest
  only:
    - deploy

# ------------------------------------------------------------------------------

build-frontend-staging-image:
  extends: .with-datomic-pro
  image: docker
  tags:
    - ht
  services:
    - docker:dind
  stage: build-docker-images
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - >
      docker build -f Dockerfile.frontend --pull
      --build-arg REST_API_URL=https://api.staging.schnaq.com
      --build-arg BUILD_HASH=$CI_COMMIT_SHORT_SHA
      --build-arg KEYCLOAK_REALM=$KEYCLOAK_REALM_STAGING
      --build-arg KEYCLOAK_CLIENT=$KEYCLOAK_CLIENT_STAGING
      --build-arg DATOMIC_REPO_USERNAME
      --build-arg DATOMIC_REPO_PASSWORD
      --build-arg ROBOTS_TXT=./robots-staging.txt
      -t ${FRONTEND_IMAGE_TAGGED}-staging .
    - docker tag ${FRONTEND_IMAGE_TAGGED}-staging $FRONTEND_IMAGE:staging
    - docker push ${FRONTEND_IMAGE_TAGGED}-staging
    - docker push $FRONTEND_IMAGE:staging
  only:
    - develop

build-backend-staging-image:
  extends: .with-datomic-pro
  image: docker
  tags:
    - ht
  services:
    - docker:dind
  stage: build-docker-images
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - >
      docker build -f Dockerfile.backend --pull
      --build-arg BUILD_HASH=$CI_COMMIT_SHORT_SHA
      --build-arg DATOMIC_REPO_USERNAME
      --build-arg DATOMIC_REPO_PASSWORD
      -t ${BACKEND_IMAGE_TAGGED}-staging .
    - docker tag ${BACKEND_IMAGE_TAGGED}-staging $BACKEND_IMAGE:staging
    - docker push ${BACKEND_IMAGE_TAGGED}-staging
    - docker push $BACKEND_IMAGE:staging
  only:
    - develop

# ------------------------------------------------------------------------------
# Deploy

deploy-staging:
  stage: deploy
  variables:
    DEPLOYMENT: staging
    DEPLOY_BACKEND_IMAGE: $CI_REGISTRY_IMAGE/backend:$CI_PIPELINE_IID-staging # here, we cannot use the constructed vars from above, because than var expansion fails.
    DEPLOY_FRONTEND_IMAGE: $CI_REGISTRY_IMAGE/frontend:$CI_PIPELINE_IID-staging
  trigger: dialogo/deployments/schnaq
  only:
    - develop

deploy-production:
  stage: deploy
  variables:
    DEPLOYMENT: production
    DEPLOY_BACKEND_IMAGE: $CI_REGISTRY_IMAGE/backend:$CI_PIPELINE_IID
    DEPLOY_FRONTEND_IMAGE: $CI_REGISTRY_IMAGE/frontend:$CI_PIPELINE_IID
  trigger: dialogo/deployments/schnaq
  only:
    - deploy
