# Fallback: Use this tag when the cs servers are down.
#default:
#  tags: [ 'bi-lab' ]

stages:
  - build
  - test
  - report
  - build-docker-images
  - deploy

cache:
  key: one-key-to-rule-them-all
  paths:
    - ./.m2/repository

variables:
  BACKEND_IMAGE: $CI_REGISTRY_IMAGE/backend
  FRONTEND_IMAGE: $CI_REGISTRY_IMAGE/frontend
  BACKEND_IMAGE_TAGGED: $CI_REGISTRY_IMAGE/backend:$CI_PIPELINE_IID
  FRONTEND_IMAGE_TAGGED: $CI_REGISTRY_IMAGE/frontend:$CI_PIPELINE_IID


# ------------------------------------------------------------------------------
# Stage "test"

test:
  image: clojure:openjdk-14-tools-deps-alpine
  before_script:
    - wget $DOWNLOAD_DEV_LOCAL && mkdir -p local_jars/dev-local && mv dev-local.jar local_jars/dev-local
  script:
    - clojure -Sdeps '{:mvn/local-repo "./.m2/repository"}' -A:test
  artifacts:
    paths:
      - target/coverage/lcov.info
    expire_in: 1 hour

test-cljs:
  image: clojure:openjdk-14-tools-deps-alpine
  before_script:
    - apk add yarn
    - yarn install
  script:
    - yarn shadow-cljs compile test

lint:
  image: clojure:openjdk-14-tools-deps-alpine
  before_script:
    - wget $DOWNLOAD_DEV_LOCAL && mkdir -p local_jars/dev-local && mv dev-local.jar local_jars/dev-local
  script:
    - clojure -Sdeps '{:mvn/local-repo "./.m2/repository"}' -A:clj-kondo --lint src
  allow_failure: true
  when: always

css-lint:
  image: node:14.8-alpine
  before_script:
    - yarn install --dev
  script:
    - yarn stylelint "resources/public/css/*.scss"
  allow_failure: true
  when: always

up-to-date?:
  image: clojure:openjdk-14-tools-deps-alpine
  before_script:
    - apk add git
    - wget $DOWNLOAD_DEV_LOCAL && mkdir -p local_jars/dev-local && mv dev-local.jar local_jars/dev-local
  script:
    - clojure -Sdeps '{:mvn/local-repo "./.m2/repository"}' -A:outdated
  allow_failure: true
  when: always


# ------------------------------------------------------------------------------
# Stage "report"

coverage-report:
  image: python:3-alpine
  stage: report
  script:
    - wget -O - https://s3.disqtec.com/schnaq-ci/lcov_cobertura.py | python3 - target/coverage/lcov.info --output target/coverage/coverage.xml
  artifacts:
    reports:
      cobertura: target/coverage/coverage.xml


# ------------------------------------------------------------------------------
# Stage "build-docker-images"

build-frontend-image:
  image: docker
  tags:
    - ht
  services:
    - docker:stable-dind
  stage: build-docker-images
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - >
      docker build -f Dockerfile.frontend
      --build-arg REST_API_URL=https://api.schnaq.com
      --build-arg BUILD_HASH=$CI_COMMIT_SHORT_SHA
      --build-arg KEYCLOAK_REALM=$KEYCLOAK_REALM
      --build-arg KEYCLOAK_CLIENT=$KEYCLOAK_CLIENT
      -t $FRONTEND_IMAGE_TAGGED .
    - docker tag $FRONTEND_IMAGE_TAGGED $FRONTEND_IMAGE:latest
    - docker push $FRONTEND_IMAGE_TAGGED
    - docker push $FRONTEND_IMAGE:latest
  only:
    - deploy

build-backend-image:
  image: docker
  tags:
    - ht
  services:
    - docker:stable-dind
  stage: build-docker-images
  before_script:
    - wget $DOWNLOAD_DEV_LOCAL && mkdir -p local_jars/dev-local && mv dev-local.jar local_jars/dev-local
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - >
      docker build -f Dockerfile.backend
      --build-arg BUILD_HASH=$CI_COMMIT_SHORT_SHA
      -t $BACKEND_IMAGE_TAGGED .
    - docker tag $BACKEND_IMAGE_TAGGED $BACKEND_IMAGE:latest
    - docker push $BACKEND_IMAGE_TAGGED
    - docker push $BACKEND_IMAGE:latest
  only:
    - deploy

build-frontend-staging-image:
  image: docker
  tags:
    - ht
  services:
    - docker:stable-dind
  stage: build-docker-images
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - >
      docker build -f Dockerfile.frontend
      --build-arg REST_API_URL=https://api.staging.schnaq.com
      --build-arg BUILD_HASH=$CI_COMMIT_SHORT_SHA
      --build-arg DATOMIC_DISCUSSION_DB_NAME=staging
      --build-arg KEYCLOAK_REALM=$KEYCLOAK_REALM_STAGING
      --build-arg KEYCLOAK_CLIENT=$KEYCLOAK_CLIENT_STAGING
      --build-arg ROBOTS_TXT=./robots-staging.txt
      -t ${FRONTEND_IMAGE_TAGGED}-staging .
    - docker tag ${FRONTEND_IMAGE_TAGGED}-staging $FRONTEND_IMAGE:staging
    - docker push ${FRONTEND_IMAGE_TAGGED}-staging
    - docker push $FRONTEND_IMAGE:staging
  only:
    - develop

build-backend-staging-image:
  image: docker
  tags:
    - ht
  services:
    - docker:stable-dind
  stage: build-docker-images
  before_script:
    - wget $DOWNLOAD_DEV_LOCAL && mkdir -p local_jars/dev-local && mv dev-local.jar local_jars/dev-local
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - >
      docker build -f Dockerfile.backend
      --build-arg BUILD_HASH=$CI_COMMIT_SHORT_SHA
      --build-arg DATOMIC_DISCUSSION_DB_NAME=production
      -t ${BACKEND_IMAGE_TAGGED}-staging .
    - docker tag ${BACKEND_IMAGE_TAGGED}-staging $BACKEND_IMAGE:staging
    - docker push ${BACKEND_IMAGE_TAGGED}-staging
    - docker push $BACKEND_IMAGE:staging
  only:
    - develop


# ------------------------------------------------------------------------------
# Deploy

deploy-staging:
  stage: deploy
  variables:
    DEPLOYMENT: staging
    DEPLOY_BACKEND_IMAGE: $CI_REGISTRY_IMAGE/backend:$CI_PIPELINE_IID-staging  # here, we cannot use the constructed vars from above, because than var expansion fails.
    DEPLOY_FRONTEND_IMAGE: $CI_REGISTRY_IMAGE/frontend:$CI_PIPELINE_IID-staging
  trigger: dialogo/deployments/schnaq
  only:
    - develop

deploy-production:
  stage: deploy
  variables:
    DEPLOYMENT: production
    DEPLOY_BACKEND_IMAGE: $CI_REGISTRY_IMAGE/backend:$CI_PIPELINE_IID
    DEPLOY_FRONTEND_IMAGE: $CI_REGISTRY_IMAGE/frontend:$CI_PIPELINE_IID
  trigger: dialogo/deployments/schnaq
  only:
    - deploy